# -*- coding: utf-8 -*-
"""
Testing whether Eddy currents in an objective partially shield
magnetic fields generated by a microwave loop

Created on December 21st, 2022

@author: mccambria
"""

import numpy as np
import utils.kplotlib as kpl
import matplotlib.pyplot as plt

mu0 = 4 * np.pi * 10**-7  # H / m
rad = 0.001 / 2  # m
current = 2 * np.sqrt(15 / 50)
current = 4.3 * np.sqrt(15 / 50)  # Matches data
# current = 14 * np.sqrt(15 / 50)


def b_field_below_loop(z):
    dist = np.sqrt(z**2 + rad**2)
    b_field = (mu0 / 2) * (rad**2 * current / (dist**3))  # T
    b_field *= 10**4  # G
    return b_field


def main():

    z_vals = 25 + np.arange(0, 600 - 30, 66.67)  # um
    z_vals_linspace = np.linspace(z_vals[0], z_vals[-1], 100)
    z_vals_linspace_m = z_vals_linspace / 1e6

    with_obj = np.array(
        [2378.8, 2254.1, 2064.1, 1830.3, 1598.2, 1291.8, 941.6, 586.3, 1.0]
    )
    # wo_obj = np.array([2378.8, 2254.1, 2064.1, 1830.3, 1598.2, 1291.8, 941.6, 586.3, 1.0])

    with_obj *= mu0 * 10**4  # From A/m to G
    # with_obj += 60

    fig, ax = plt.subplots()

    kpl.plot_points(ax, z_vals, with_obj, label="GPRMax")

    ideal = [b_field_below_loop(z) for z in z_vals_linspace_m]
    kpl.plot_line(ax, z_vals_linspace, ideal, label="Analytical")

    ax.set_xlabel("Z position (um)")
    ax.set_ylabel("B field (G)")

    ax.legend()


if __name__ == "__main__":

    kpl.init_kplotlib()

    main()

    plt.show(block=True)
